sudo: required
language: generic
dist: xenial

env:
  - PEXT_BUILD_PORTABLE=0
  - PEXT_BUILD_PORTABLE=1

os:
  - osx
  - linux

script:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then pip3 install tox-travis; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash -xe travis/bootstrap-container.sh; fi
  # beware: the line below is a DIRTY HACK -- it will override the system pip -- the proper way to do this would be a virtualenv
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://bootstrap.pypa.io/get-pip.py -O- | sudo python3.6; sudo pip install tox-travis; fi
  # run tests
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then xvfb-run tox -v; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then tox -v; fi
  # build dmg for macOS
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then bash -xe travis/build-dmg.sh; fi
  # build AppImage for Linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir -p build; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd build; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then bash -xe ../travis/build-appimage.sh; fi

jobs:
  include:
    - stage: deploy
      install: skip
      script:
        - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh
        - if [ "$TRAVIS_BRANCH" != "master" ]; then export TRAVIS_EVENT_TYPE=pull_request; fi
        - bash upload.sh Pext*.zip Pext*.dmg Pext*.AppImage*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - # Also, don't build i18n, the only changes are uncompiled translation files
    - i18n

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MFN5bHZpZUxvcnh1JTNBbWF0cml4Lm9yZy8lMjFQcEdURlpIeXVpY3ZQRGVNVUglM0FtYXRyaXgub3Jn"
        on_success: always
        on_failure: always
        on_start: never
