language: generic
os:
  - osx

before_install:
  - brew update
  - brew install libgit2 libnotify python3
  - pip3 install pygit2 pyqt5 urllib3
  - shopt -s expand_aliases
  - alias sha256sum="shasum -a 256" # For upload.sh

install:
  - ./build_mac_app.sh

after_success:
  - pushd dist
  - zip Pext.app.zip -r Pext.app
  - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - env TRAVIS_EVENT_TYPE=pull_request bash upload.sh Pext.app.zip
