language: generic
os:
  - osx

before_install:
  - brew update
  - brew upgrade python
  - pip3 install dulwich pyqt5 urllib3

install:
  - ./build_mac_app.sh

after_success:
  - pushd dist
  - zip Pext.app.zip -r Pext.app
  - wget https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - env TRAVIS_EVENT_TYPE=pull_request bash upload.sh Pext.app.zip
